global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'command-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['command-app:8081']

  - job_name: 'query-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['query-app:8082'] 